"""Popular stocks, ETFs and cryptocurrencies to suggest. Any other Yahoo Finance ticker still works."""

STOCKS = {
    "AAPL": "Apple",
    "MSFT": "Microsoft",
    "NVDA": "NVIDIA",
    "TSLA": "Tesla",
    "AMZN": "Amazon",
    "GOOGL": "Alphabet (Google)",
    "META": "Meta Platforms",
    "NFLX": "Netflix",
    "AMD": "AMD",
    "INTC": "Intel",
    "PLTR": "Palantir",
    "AVGO": "Broadcom",
    "UBER": "Uber",
    "JPM": "JPMorgan Chase",
    "V": "Visa",
    "WMT": "Walmart",
    "COST": "Costco",
    "KO": "Coca-Cola",
    "MCD": "McDonald's",
    "DIS": "Disney",
    "NKE": "Nike",
    "BA": "Boeing",
    "SPY": "S&P 500 ETF",
    "QQQ": "Nasdaq-100 ETF",
    "VOO": "Vanguard S&P 500 ETF",
    "DIA": "Dow Jones ETF",
    "GLD": "Gold ETF",
}

CRYPTO = {
    "BTC-USD": "Bitcoin",
    "ETH-USD": "Ethereum",
    "SOL-USD": "Solana",
    "XRP-USD": "XRP",
    "BNB-USD": "BNB",
    "DOGE-USD": "Dogecoin",
    "ADA-USD": "Cardano",
    "TRX-USD": "TRON",
    "AVAX-USD": "Avalanche",
    "LINK-USD": "Chainlink",
    "SHIB-USD": "Shiba Inu",
    "DOT-USD": "Polkadot",
    "BCH-USD": "Bitcoin Cash",
    "LTC-USD": "Litecoin",
    "XLM-USD": "Stellar",
    "HBAR-USD": "Hedera",
    "ATOM-USD": "Cosmos",
    "ETC-USD": "Ethereum Classic",
    "XMR-USD": "Monero",
}
